set(CVD_LINUX false)
set(CVD_MSWIN false)
set(CVD_MACOS false)
set(CVD_MSWSL false)
set(CVD_OTHER false)

if (WIN32 AND CMAKE_SYSTEM_VERSION)
    message(STATUS "OS: Windows")
    set(CVD_MSWIN true)
elseif (APPLE)
    message(STATUS "OS: macOS")
    set(CVD_MACOS true)
elseif (UNIX AND ("${CMAKE_HOST_SYSTEM_NAME}" MATCHES "Linux"))
    set(CVD_LINUX true)

    if (CMAKE_HOST_SYSTEM MATCHES "Microsoft")
        set(CVD_MSWIN true)
        set(CVD_MSWSL true)
        message(STATUS "OS: Windows (as Linux via WSL)")
    else ()
        message(STATUS "OS: Linux")
    endif ()
else ()
    set(CVD_OTHER true)
endif ()

if (CVD_MSWSL OR CVD_OTHER)
    message(FATAL_ERROR "Current OS Status: ***UNSUPPORTED***")
endif ()